
###-----Load Packages----

if (!require("pacman")) install.packages("pacman")
pacman::p_load(ggplot2,
               stats,
               statmod,
               tidyverse,
               pROC,
               corrplot,
               hablar,
               ggpubr,
               plotly,
               ggsci,
               magrittr,
               gghighlight
)

#optionally set scientific notation
options(scipen = 999)
set.seed(1234)


###-----Units-----

get.pretty.factor <- function(cytokines) {
    lapply(cytokines, function(x) as.character(units$Factor[match(x, units$Var)])) %>%
        unlist()
}
get.pretty.name <- function(cytokines) {
    lapply(cytokines, function(x) as.character(units$Name[match(x, units$Var)])) %>%
        unlist()
}
get.pretty.units <- function(cytokines) {
    lapply(cytokines, function(x) as.character(units$Units[match(x, units$Var)])) %>%
        unlist()
}

###-----Modeling----

# Create glm for each protein
glmFits <- function(cases.df, cyto, ...) {

    fmla <- sapply(1:length(cyto), function(x, var = cyto) {
        as.formula(paste0("as.factor(Status) ~ ", var[x]))
    })


    glmFits <- lapply(fmla, function(y) {
        glm(y, data=cases.df, family = binomial, na.action = na.omit)
    })

    return(glmFits)
}



# Get the coefficients of the glm fit
glmCoefs <-  function(glmFits, cytokines=cytokines, ...)  {
    # get glm coefficients and significance from fits (glmFits)
    fit.intercept <- sapply(1:length(cytokines),
                            function(x) (coef(glmFits[[x]])[1] ) )
    fit.cytokine <- sapply(1:length(cytokines),
                           function(x) (coef(glmFits[[x]])[2] ) )
    p.value <- sapply(glmFits, function(x) summary(x)$coefficients [8])

    glmCoefs <- cbind(fit.intercept, fit.cytokine, p.value) %>%
        set_rownames(cytokines)

    return(glmCoefs)
}

# find optimal accuracy of ROC fit
# arguments:
# 1. model fits generated by glmFits
# 2. list of cytokines/proteins, i.e. cytokines = c("prot1", "prot2", ...)

rocFits <- function(glmFits, cytokines=cytokines, ...) {

    # calculate the ROC curve
    rocFits <- lapply(glmFits, function(x)
        roc(response = x$y, predictor = x$fitted.values, na.rm = T,
            # auc = TRUE, levels = c(0, 1), direction = "auto",
            quiet = T) ) #%>% names(cytokines)

    return(rocFits)
}

# Get all the info about each ROC curve
rocCoords <- function(rocFits, glmCoefs, cytokines=cytokines, ...) {
    # AUCs of each ROC curve
    AUC <- sapply(rocFits, function(x) x$auc )

    # coordinates of the best (top-left corner) threshold of ROC curve
    # and measures of prediction accuracy
    rocCoords <- sapply(rocFits, function(y)
        coords(y, ret=c("threshold", "specificity",
                        "sensitivity", "accuracy",
                        "ppv", "npv", "tpr", "tnr",
                        "fnr", "fpr", "fdr",
                        "tn", "tp", "fn", "fp"),
               transpose=T,
               x="best",
               best.method="c"
               ),
        simplify = T) %>%
        data.frame() %>%
        t() %>% data.frame() %>%
        cbind(AUC, glmCoefs) %>%
        mutate(thresh.val = (log(threshold/(1-threshold)) -
                                 fit.intercept) / fit.cytokine) %>%
        set_rownames(cytokines)

    return(rocCoords)
}


# Usage: set your list of cytokines/proteins, e.g.:
cytokines = c("PAI1", "TM")

# then run each function, saving each to its own variable

glmDat <- glmFits(adm, cytokines)

glmCo <- glmDat %>%
    glmCoefs(cytokines)

rocData <- glmDat %>%
    rocFits(cytokines)

names(rocData) <- cytokines

# Save the final results
rocRes <- rocCoords(rocFits = rocData, glmCoefs = glmCo, cytokines)

# Format the results (optional)
rocResFormat <- rocRes %>% rownames_to_column("Var") %>%
    left_join(units, by = "Var") %>%
    select(Name, AUC, Threshold=thresh.val, Units, p.value,
           specificity, sensitivity, ppv, npv) %>%
    mutate_if(is.numeric, round, 3)



# Function to plot the ROC curve for each protein
r <- function(f){
    pROC::ggroc(rocData[f])+
        coord_fixed() +
        scale_fill_discrete(labels=c(get.pretty.name(f)))+
        theme_pubr() +
        theme(#legend.position = c(0.65, 0.4),
            # legend.text = element_text(size = 12),
            legend.title = element_blank())

} %>% ggplotly(height = 400, width = 600)

# Usage examples:
r(cytokines)
r("PAI1")
r(c("PAI1", "TM"))

# Note:
# Can use a loop or some method like RShiny to plot proteins separately,
    # otherwise all proteins will be plotted on the same graph.
# Since it is graphed with plotly, you can click/double click on
    # proteins in the legend to hide (on click) or show only that protein (on
    # double click).




# Confusion matrix
conMat <- rocRes %>% select(tp, fn, fp, tn) %>%
    rownames_to_column("var")

confusionMat <- lapply(1:length(cytokines),
                       function(x) data.frame(
                           "Pred" = c("Pred Surv", "Pred Fatal"),
                           "Survivor" = c(conMat$tp[x], conMat$fn[x]),
                           "Fatal" = c(conMat$fp[x], conMat$tn[x])) %>%
                           column_to_rownames(var="Pred")
)
names(confusionMat) <- cytokines

confusionMat


###-----Correlations-----------

# Provide dataframe with only continuous variables (e.g. proteins)
    # cases = dataframe with proteins (columns) by samples (rows)
    # rects = an integer, the number of rectangles to put in the plot,
        #play around with the number



cyto.corr <- function(cases, rects) {
    correlations <- abs(cor(cases, method = "pearson", use = "complete.obs"))

    corrplot(correlations,
             cl.lim=c(0,max(correlations)),
             method="circle",
             order = "hclust",
             hclust.method = "complete",
             tl.col="black",
             tl.srt=45,
             addrect = rects,
             is.corr=FALSE)
}

# set the number of boxes in your plot
rects = 3
# Run the function
cyto.corr(cases, rects)


